# RDS 정보 저장 - DB이름, 유저명 등 비밀번호 이외의 정보를 저장
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_HOST: "rds.tf.private.com"  # RDS 엔드포인트와 연결되어있는 Route53 FQDN
  MYSQL_PORT: "3306"

