# 컨테이너 실행
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: secrets-access-sa  # IRSA 적용 추가
      containers:
      - name: test-container
        image: <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/test-ecr-namespace/test-ecr:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mysql-config
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: AWS_SECRET_NAME
          value: "rds!xxxxxxxxxxxxx"   # Secrets Manager의 시크릿 이름
        - name: AWS_REGION
          value: "ap-northeast-2"
